// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-1HJuACF7fWklPRbKmrV-qrZ09kgn1DM',
    appId: '1:1043047803888:web:9f4e5751e75a5d03a24b35',
    messagingSenderId: '1043047803888',
    projectId: 'flutter-database-app-5a5c7',
    authDomain: 'flutter-database-app-5a5c7.firebaseapp.com',
    storageBucket: 'flutter-database-app-5a5c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXu3QrCSIclaDq500IXtN6fSYxdmd4pJY',
    appId: '1:1043047803888:android:aba122d237947198a24b35',
    messagingSenderId: '1043047803888',
    projectId: 'flutter-database-app-5a5c7',
    storageBucket: 'flutter-database-app-5a5c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhbBOUAFo9goh6DrVWuMfgxG5RWjTeFuw',
    appId: '1:1043047803888:ios:586870f75d044ba1a24b35',
    messagingSenderId: '1043047803888',
    projectId: 'flutter-database-app-5a5c7',
    storageBucket: 'flutter-database-app-5a5c7.firebasestorage.app',
    iosBundleId: 'com.example.flutterDatabaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhbBOUAFo9goh6DrVWuMfgxG5RWjTeFuw',
    appId: '1:1043047803888:ios:586870f75d044ba1a24b35',
    messagingSenderId: '1043047803888',
    projectId: 'flutter-database-app-5a5c7',
    storageBucket: 'flutter-database-app-5a5c7.firebasestorage.app',
    iosBundleId: 'com.example.flutterDatabaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-1HJuACF7fWklPRbKmrV-qrZ09kgn1DM',
    appId: '1:1043047803888:web:054b774a8f2ff8a8a24b35',
    messagingSenderId: '1043047803888',
    projectId: 'flutter-database-app-5a5c7',
    authDomain: 'flutter-database-app-5a5c7.firebaseapp.com',
    storageBucket: 'flutter-database-app-5a5c7.firebasestorage.app',
  );
}
